## Start Minikube with kvm2 driver

[source,bash]
----
minikube delete
minikube config set driver kvm2
touch /tmp/config && export KUBECONFIG=/tmp/config
minikube start --memory 16384 --cpus 4
----

## Create confluent k8s namespace

[source,bash]
----
kubectl create namespace confluent
kubectl config set-context --current --namespace confluent
----

## Add confluent repo to helm

[source,bash]
----
helm repo add confluentinc https://packages.confluent.io/helm
helm repo update
----

## Option 1: Install confluent-for-kubernetes operator from Confluent’s Helm repo

[source,bash]
----
helm upgrade --install confluent-operator confluentinc/confluent-for-kubernetes
----

## Option 2: Install confluent-for-kubernetes operator using the download bundle with license key

[source,bash]
----
wget https://confluent-for-kubernetes.s3-us-west-1.amazonaws.com/confluent-for-kubernetes-2.2.0.tar.gz
tar xvf confluent-for-kubernetes-2.2.0.tar.gz
helm upgrade --install confluent-operator ./confluent-for-kubernetes-2.2.0-20211101/helm/confluent-for-kubernetes --set licenseKey=<CFK license key>
----

## Expose kafka and other components to external access using Kubernetes Load Balancer

Edit file _k8s/confluent-platform-reducted.yaml_ and add the value of your Kubernetes cluster DOMAIN (default is _cluster.local_) in section:

[source,yaml]
----
loadBalancer:
  domain: cluster.local
----

## Install Confluent components: 3 zk, 3 brokers, 1 control center

[source,bash]
----
kubectl apply -f k8s/confluent-platform-reducted.yaml
----

## Verify events and pods

[source,bash]
----
watch -n 5 "kubectl get events --sort-by='.lastTimestamp'"
watch -n 5 "kubectl get pods"
----

## LoadBalancer access using minikube

In a new terminal run (It must be run in a separate terminal window to keep the LoadBalancer):

[source,bash]
----
minikube tunnel
----

## Get Services status

[source,bash]
----
kubectl get services
----

Check values for column: *EXTERNAL-IP* for services:

. kafka-bootstrap-lb
. kafka-0-lb
. kafka-1-lb
. kafka-2-lb
. controlcenter-bootstrap-lb

These IPs will be used for external access to kafka and control center.

Add DNS records for the brokers and control center the URLs (e.g. /etc/hosts):

. kafka.$DOMAIN (e.g. kafka.cluster.local)
. b0.$DOMAIN (e.g. b0.cluster.local)
. b1.$DOMAIN (e.g. b1.cluster.local)
. b2.$DOMAIN (e.g. b2.cluster.local)
. controlcenter.$DOMAIN (e.g. controlcenter.cluster.local)

## Connect to Contol Center

Open a browser pointing to http://controlcenter.$DOMAIN (e.g.http://controlcenter.cluster.local)


## Create a Topic named test-1

[source,bash]
----
kubectl apply -f k8s/topic.yml
----

## Produce messages to topic test-1

Create the producer app from your host:

[source,bash]
----
 kafka-producer-perf-test \
            --topic test-1  \
            --record-size 64 \
            --throughput 1 \
            --producer-props bootstrap.servers=kafka.cluster.local:9092 \
            --num-records 230400
----

## Tear Down

Shut down Confluent Platform and the data:

[source,bash]
----
kubectl delete -f k8s/topic.yml
kubectl delete -f k8s/confluent-platform-reducted.yaml
helm delete confluent-operator
----

Delete namespace confluent:

[source,bash]
----
kubectl delete namespace confluent
----
